name: tests

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest pytest-playwright
          python -m playwright install --with-deps chromium

      - name: Run pytest (headed)
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          pytest -v --headed